name: CI-TEST
on: [push]
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: print host
        env:
          moon: ${{ secrets.HOST }}
          testval: 1234
          testVal: {{ 1a2a3a4atest }}
        run: echo host $moon $testVal $testval
      - name: ssh test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al
